name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Rename Project in firebaserc
        run: echo "{\"projects\":{\"default\":\"dd-dapp\"}}" >> .firebaserc
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting --project dd-dapp
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
